[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.23"
optimizer = true
optimizer_runs = 200
via_ir = true
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/",
    "openzeppelin-contracts/=lib/openzeppelin-contracts/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
[rpc_endpoints]
mainnet = "https://eth-mainnet.alchemyapi.io/v2/YOUR_API_KEY"
sepolia = "https://eth-sepolia.alchemyapi.io/v2/YOUR_API_KEY"

[etherscan]
mainnet = { key = "YOUR_ETHERSCAN_API_KEY" }
sepolia = { key = "YOUR_ETHERSCAN_API_KEY" }
